### ISSUE TITLE
Set Default User Account

### ISSUE THREAD

**Issue by MarvelMash** [ManuelReschke/go-pd#11]
Is it possible to store api key somewhere so we can use "go-pd upload file.txt" and it uploads to user account directly

**Comment by ManuelReschke** [comment]
@MarvelMash , do you want a config.yml or something?

**Comment by ManuelReschke** [comment]
In the next version v1.5.0 you can set an ENV value and then you can just enter go-pd upload xy.

set env in linux
`export PIXELDRAIN_API_KEY=32f01b5e-8d52-49d6-80a7-XXXXXXXX`

upload with verbose info
`./go-pd upload cat_thumbnail.jpg -v

Using API Key from environment variable: PIXELDRAIN_API_KEY
"cat_thumbnail.jpg" uploaded 100.00%
Successful! Anonymous upload: false | ID: yoSKrCib | URL: https://pixeldrain.com/u/yoSKrCib
`
