### ISSUE TITLE
VirusTotal report for Windows executable

### ISSUE THREAD

**Issue by YisusChrist** [ManuelReschke/go-pd#7]
Right after downloading the latest release available for [Windows](https://github.com/ManuelReschke/go-pd/releases/download/v1.4.0/go-pd_1.4.0_windows_amd64.tar.gz) I decided to scan the binary shipped and here it is the report:

https://www.virustotal.com/gui/file/6b0f47a6157f5b3028dbde1c8871899a975fb8af34a310a532c187716573e04f

There are 2 engines that report it as a malicious file. I've taken a look at the code and I obviously don't see anything malicious around. I think you should take a look at the report for a convenient clean-up to avoid those detections.

**Comment by ManuelReschke** [comment]
Hi, thanks for the report. But just send a false positve report to MS.
[https://learn.microsoft.com/en-us/microsoft-365/security/defender/m365d-autoir-report-false-positives-negatives?view=o365-worldwide](https://learn.microsoft.com/en-us/microsoft-365/security/defender/m365d-autoir-report-false-positives-negatives?view=o365-worldwide)

I dont know what i should do now. Its not an virus and its open source...
