### ISSUE TITLE
Downloads stop after 1gb

### ISSUE THREAD

**Issue by dan195794** [ManuelReschke/go-pd#8]
Hey, I'm getting this issue in my debian-arm box.
It stops after about 1gb so the output file is corrupt.
Ethernet is wired.

./go-pd download -v https://pixeldrain.com/u/**(file)**
Error: local error: tls: bad record MAC

**Comment by Fornax96** [comment]
This error means that some router between you and the pixeldrain server has altered a TCP packet, now the TLS checksum is failing and thus the stream is ended.

**Comment by ManuelReschke** [comment]
@dan195794 is this error reproducible or a one time error? I could implement a retry mechanic if you want. I am waiting for your feedback.
