### ISSUE TITLE
Failed to download some files.

### ISSUE THREAD

**Issue by pikach0o** [ManuelReschke/go-pd#9]
For some reason download is failed with the Linux package in Debian 9.
Downloaded fine with Linux package in WSL, and with Windows package in Win11.
Other smaller items successfully downloaded.

error displayed:
`Error: json: cannot unmarshal number 3436873471 into Go struct field ResponseFileInfo.bandwidth_used of type int`

https://pixeldrain.com/l/MN5CyAyT#item=1 >> https://pixeldrain.com/u/Wpggfbtp
https://pixeldrain.com/l/MN5CyAyT#item=3 >> https://pixeldrain.com/u/8r2cfLKM

**Comment by Fornax96** [comment]
I think you're running a 32 bit executable. 32 bit ints can only hold file sizes up to 2 GiB. Try installing a 64 bit release.

Ideally all ints from the API should be saved as int64.

**Comment by ManuelReschke** [comment]
I will change all to int64 and push a fix soon as possible.

**Comment by ManuelReschke** [comment]
New release with fix https://github.com/ManuelReschke/go-pd/releases/tag/v1.4.1

**Comment by ManuelReschke** [comment]
@pikach0o can you confirm that it work?

**Comment by pikach0o** [comment]
> @pikach0o can you confirm that it work?

Sorry for the late reply.
I confirm that version 1.4.1 linux_386 works in my vps, with those two files.

Thank you for the fix.
